# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='servers.proto',
  package='pspnet_cluster',
  syntax='proto3',
  serialized_pb=_b('\n\rservers.proto\x12\x0epspnet_cluster\"\x13\n\x04path\x12\x0b\n\x03url\x18\x01 \x01(\t\"6\n\x07NDArray\x12\r\n\x05\x61rray\x18\x01 \x03(\x01\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\"@\n\rNDArrayPacked\x12\x11\n\x05\x61rray\x18\x01 \x03(\x01\x42\x02\x10\x01\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t2S\n\rpspnet_server\x12\x42\n\x11get_server_memory\x12\x14.pspnet_cluster.path\x1a\x17.pspnet_cluster.NDArrayb\x06proto3')
)




_PATH = _descriptor.Descriptor(
  name='path',
  full_name='pspnet_cluster.path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='pspnet_cluster.path.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=52,
)


_NDARRAY = _descriptor.Descriptor(
  name='NDArray',
  full_name='pspnet_cluster.NDArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='pspnet_cluster.NDArray.array', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='pspnet_cluster.NDArray.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='pspnet_cluster.NDArray.dtype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=108,
)


_NDARRAYPACKED = _descriptor.Descriptor(
  name='NDArrayPacked',
  full_name='pspnet_cluster.NDArrayPacked',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='pspnet_cluster.NDArrayPacked.array', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='pspnet_cluster.NDArrayPacked.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='pspnet_cluster.NDArrayPacked.dtype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=174,
)

DESCRIPTOR.message_types_by_name['path'] = _PATH
DESCRIPTOR.message_types_by_name['NDArray'] = _NDARRAY
DESCRIPTOR.message_types_by_name['NDArrayPacked'] = _NDARRAYPACKED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

path = _reflection.GeneratedProtocolMessageType('path', (_message.Message,), dict(
  DESCRIPTOR = _PATH,
  __module__ = 'servers_pb2'
  # @@protoc_insertion_point(class_scope:pspnet_cluster.path)
  ))
_sym_db.RegisterMessage(path)

NDArray = _reflection.GeneratedProtocolMessageType('NDArray', (_message.Message,), dict(
  DESCRIPTOR = _NDARRAY,
  __module__ = 'servers_pb2'
  # @@protoc_insertion_point(class_scope:pspnet_cluster.NDArray)
  ))
_sym_db.RegisterMessage(NDArray)

NDArrayPacked = _reflection.GeneratedProtocolMessageType('NDArrayPacked', (_message.Message,), dict(
  DESCRIPTOR = _NDARRAYPACKED,
  __module__ = 'servers_pb2'
  # @@protoc_insertion_point(class_scope:pspnet_cluster.NDArrayPacked)
  ))
_sym_db.RegisterMessage(NDArrayPacked)


_NDARRAYPACKED.fields_by_name['array'].has_options = True
_NDARRAYPACKED.fields_by_name['array']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))

_PSPNET_SERVER = _descriptor.ServiceDescriptor(
  name='pspnet_server',
  full_name='pspnet_cluster.pspnet_server',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=176,
  serialized_end=259,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_server_memory',
    full_name='pspnet_cluster.pspnet_server.get_server_memory',
    index=0,
    containing_service=None,
    input_type=_PATH,
    output_type=_NDARRAY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PSPNET_SERVER)

DESCRIPTOR.services_by_name['pspnet_server'] = _PSPNET_SERVER

# @@protoc_insertion_point(module_scope)
