# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import servers_pb2 as servers__pb2


class pspnet_serverStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_server_memory = channel.unary_unary(
        '/pspnet_cluster.pspnet_server/get_server_memory',
        request_serializer=servers__pb2.path.SerializeToString,
        response_deserializer=servers__pb2.NDArray.FromString,
        )


class pspnet_serverServicer(object):
  """Interface exported by the server.
  """

  def get_server_memory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_pspnet_serverServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_server_memory': grpc.unary_unary_rpc_method_handler(
          servicer.get_server_memory,
          request_deserializer=servers__pb2.path.FromString,
          response_serializer=servers__pb2.NDArray.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pspnet_cluster.pspnet_server', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
