account_01: &account_01
 username: guxi
 password: cft6&UJM
account_02: &account_02
 username: guxi
 password: dHtFkI6g



client:
 -
  name: pelican01
  host: pelican01.eecs.oregonstate.edu
  port: 22
  <<: *account_01
 -
  name: pelican02
  host: pelican02.eecs.oregonstate.edu
  port: 22
  <<: *account_01
 -
  name: pelican03
  host: pelican03.eecs.oregonstate.edu
  port: 22
  <<: *account_01
 -
  name: pelican04
  host: pelican04.eecs.oregonstate.edu
  port: 22
  <<: *account_01
 -
  name: star_gpu_on_star_lab
  host: localhost
  port: 50022
  <<: *account_02
# -
#  name: star_gpu_local
#  host: localhost
#  port: 22
#  <<: *account_02
client_type:
  pelican:
    - pelican01
    - pelican02
    - pelican03
    - pelican04
  core:
#    - star_gpu_on_star_lab
#    - star_gpu_local
    - local
proxy:
  service:
    core:
      -
        type: ssh
        avaliable: pelican
        port: 22
      -
        type: app_comm
        avaliable: pelican
      -
        type: log
        avaliable: pelican
      -
        type: manager
        avaliable: pelican
