services:
  manager:
    port: 30031
    type: sio
  log:
    port: 30001
    type: sio
  app_comm:
    port: 30021
    type: sio
  ssh:
    port: 50022
    type: tcp
  mysql:
    port: 33060
